config/routes.rb
Rails.application.routes.draw do
root 'products#index'

  resources :products do
  resources :reviews
  end

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :description, :name, presence: true
	validates :price_in_cents, numericality: {only_integer: true}

	def formatted_price
	    price_in_dollars = price_in_cents.to_f / 100
	    sprintf("%.2f", price_in_dollars)
  	end

  	has_many :reviews
  	has_many :users, through: :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :user
	belongs_to :product

	validates :comment, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :name, :email, presence: true
	validates :email, uniqueness: true 

	# validates :name_start_with_a
	has_many :reviews
	has_many :products, through: :reviews


	# private 
	# def name_starts_with_a
	# 	if name[0] != "A"
	# errors.add(:name, "Doesn't start with A")
	# 	end
	# end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

   def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in"
      redirect_to new_session_path
    end
  end

  private

  def current_user
    if !User.find_by_id(session[:user_id])
      session[:user_id] = nil 
    end
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
     @products = if params[:search]
      Product.where("LOWER(name) LIKE LOWER(?)", "%#{params[:search]}%").page(params[:page])
    else
      Product.order('products.created_at DESC').page(params[:page])
    end


   respond_to do |format|
      format.html
      format.js
    end

  end

  def show
  	@product = Product.find(params[:id])
	  	 if current_user
	    @review = @product.reviews.build
	  	end
  end

  def new
  	@product = Product.new
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def create 
  	@product = Product.new(product_params)
  		if @product.save 
  			redirect_to @product
  		else
        flash.now[:alert] = "Error Error Error"
  			render :new
  		end
  end


  def update
  	@product = Product.find(params[:id])

  	if @product.update_attributes(product_params)
  		redirect_to product_path(@product)
  	else
  		render :edit
  	end
  end


  def destroy
  	@product = Product.find(params[:id])
  	@product.destroy 
  	redirect_to products_path 
  end 

  private 
  def product_params
  	params.require(:product).permit(:name, :description, :price_in_cents)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :load_product
  before_filter :ensure_logged_in, only: [:create, :destroy]
  def show
    @review = Review.find(params[:id])
  end

  def create
    @review = @product.reviews.build(review_params)
    @review.user = current_user

    # Check out this article on [.build](http://stackoverflow.com/questions/783584/ruby-on-rails-how-do-i-use-the-active-record-build-method-in-a-belongs-to-rel)
    # You could use a longer alternate syntax if it makes more sense to you
    # 
    # @review = Review.new(
    #   comment: params[:review][:comment],
    #   product_id: @product.id,
    #   user_id: current_user.id
    # )
     respond_to do |format|
        if @review.save
          format.html {redirect_to product_path(@product), notice: 'Review created successfully'}
          format.js {}
        else
          format.html{ render 'products/show', alert: 'Error.  Failed to create Review'}
          format.js {}
        end
     end

  end

  def edit
    @review = Review.find(params[:id])
    load_product
  end

  def update
    @review = Review.find(params[:id])

    if @review.update_attributes(review_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to @product
  end

  private
  def review_params
    params.require(:review).permit(:comment, :product_id)
  end

  def load_product
    @product = Product.find(params[:product_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to products_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end
  

  def destroy
  	 session[:user_id] = nil
    redirect_to products_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
	  @user = User.new(user_params)
	    if @user.save
	   		redirect_to products_url, notice: "Signed up!"
	    else
	      render "new"
   	  end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav>
    <div class="nav">
        <div class="container">
          <div class b= "row">
         <div class="col-md-4">
           </div>
        </div>
             <div class = "col-md-4">
               </div>
               <div class = "col-md-4">
               </div>
              <div class = "navtitles">
            <ul class = "pull-left">
                  <li><a href = "/products/new">Create a Product</a></li>
                  <li><a href="/products">View all Products</a></li>
                <!--   <li><a href="/contacts/show_contact">View a contact</a></li>
                  <li><a href="">Delete a contact</a></li>
                  <li><a href="">Display an attribute</a></li> -->
                  <li><a>
      <% if current_user %>
        Signed in as <%= current_user.name %> <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> <%= link_to "Sign up", new_user_path %>
      <% end %>
    </a></li>
                </ul>
            </div>  
        </div>
    </div>
  </nav>

 
<%= yield %>

   <% if flash[:notice] %>
      <p id="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p id="alert"><%= flash[:alert] %></p>
    <% end %>


 <p class="userinfo">
      <% if current_user %>
        Signed in as <%= current_user.name %> <%= link_to "Log out", session_path("current"), :method => :delete %>
      <% else %>
        <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
      <% end %>
    </p>

</body>
</html>

app/views/products/_product.html.erb
		<p>
		<br>
		<%= product.name %>
		<br>
		<%= product.description %>
		<br>
		Price: $<%= product.formatted_price %>
		<br>
		 <%= product.created_at %>
		<br>
		<%= link_to "View More Details", "/products/#{product.id}" %>
		</p>
		

app/views/products/_review.html.erb
 <p>Reviews for <%= @product.name %></p>
    <% @product.reviews.each do |review| %>
      <p>
        <%= review.comment %>
    
        <% if review.user != nil %>
          <em> by <%= review.user.email %></em>
        <br><br>
          Added on: <%= review.created_at %>
        <% end %>
      </p>
        <% if review.user_id == session[:user_id] %>
          <%= link_to "Delete", product_review_path(@product, review), method: :delete, data: {confirm: "Are you sure you want to delete this reservation"} %>
          <%= link_to "Edit", edit_product_review_path(@product, review), data: {confirm: "Are you sure you want to edit your reservation?"} %>
          
      <% end %>
    <% end %>

app/views/products/_review_form_errors.html.erb
<% if @review.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

          <ul>
          <% @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
<% end %>

app/views/products/edit.html.erb
	<h1>Products#edit</h1>
<p>Find me in app/views/products/edit.html.erb</p>
	<%= form_for @product do |f| %>
		<br>
		<%= f.label :name %>
		<br>
		<%= f.text_field :name %>
		<br>
		<%= f.label :descripton %>
		<br>
		<%= f.text_area :description %>
		<br>
		<%= f.label :price_in_cents %>
		<br>
		<%= f.text_field :price_in_cents %>
		<br>
		<%= f.submit %> 
		<br>

		<% if @product.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
			  <ul>
		      <% @product.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		      </ul>
		    </div>
  		<% end %>

<% end %>

app/views/products/index.html.erb
<h1 class = "titlepage">List of the Products Page<br></h1>

	<%= form_tag products_path, method: :get, authentication: false, id: 'search-form' do %>
	  <%= text_field_tag :search, params[:search] %>
	  <%= submit_tag "Search" %>
	<% end %>

	<p>Check out each product</p>
<!--   <small><%= page_entries_info @products %></small> -->
	<div id = "products">
		<%= render @products %>
	</div>

  <%= paginate @products %>
 

  <br>

 

app/views/products/index.js.erb
<% if params[:search] && params[:page].nil? %>
  $('#products').html("<%= j(render @products) %>");
<% else %>
  $('#products').append("<%= j(render @products) %>");
  $('.pagination').replaceWith('<%= j paginate(@products) %>');
<% end %>

app/views/products/new.html.erb
	<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>
<p> hello </o>
	<%= form_for @product do |f| %>
		<br>
		<%= f.label :name %>
		<br>
		<%= f.text_field :name %>
		<br>
		<%= f.label :descripton %>
		<br>
		<%= f.text_area :description %>
		<br>
		<%= f.label :price_in_cents %>
		<br>
		<%= f.text_field :price_in_cents %>
		<br>
		<%= f.submit "save" %> 
		<br>

		<% if @product.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@product.errors.count, "things") %> prohibited this product from being saved:</h2>
			  <ul>
		      <% @product.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		      </ul>
		    </div>
  		<% end %>
	<% end %>



  

app/views/products/show.html.erb
	<%= @product.name %> 
	<br>
	<%= @product.description %>
	<br>
	<%= @product.formatted_price %>
  <br>
  <%= @product.created_at %>
	<br>
	<%= link_to "Back to all the Products", products_url %>
	<br>
	<%= link_to "Edit product", edit_product_path(@product) %>
	<br>
	<%= link_to "Delete", @product, method: :delete, data: {confirm: "Are you sure you want to delete this product"} %>



 <h3>Reviews</h3>

  <div id = "review-list">
     <%= render :partial => "review" %>
  </div>



<% if current_user %>
  <h4>New Review</h4>


  <%= form_for([@product, @review], :remote => true) do |f| %>
    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
    <div id="review-form-errors">
          <%= render :partial => "/products/review_form_errors" %>
    </div>
  <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to add a review.</p> 
<% end %>

<script type="text/javascript">
  $(function() {
     $("#new_review")
        .on('ajax:beforeSend', function() { // set this code to happen just before the ajax request is made
          $("input[type='submit']") // make changes to the submit button
            .val('Saving...') // change the text on the button
            .attr('disabled', 'disabled'); // disable the button
        })
        .on('ajax:complete', function() {
          $("input[type='submit']")
            .val('Create Review')
            .removeAttr('disabled');
        });
  });
</script>


  

app/views/reviews/create.js.erb
<% if @review.errors.present? %>
  $("#review-form-errors").html("<%= escape_javascript(render(:partial => '/products/review_form_errors')) %>");
<% else %>
  $("#review-form-errors").html("");
  $("#review-list").html("<%= escape_javascript(render(:partial => '/products/review')) %>");
  $("#new_review")[0].reset();
<% end %>

app/views/reviews/edit.html.erb
  <%= form_for([@product, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

  <%= link_to "Back to product", product_path(@product) %>bundle exec rake console

  

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Sign up didn't go through</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= f.label :name %><br/>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>	